/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Terraria-inspired pixelated theme
        'gh-canvas-default': '#2d1b2e',
        'gh-canvas-subtle': '#3d2946',
        'gh-canvas-inset': '#1f1626',
        'gh-border-default': '#8b6d9c',
        'gh-border-muted': '#5c4a68',
        'gh-neutral-emphasis': '#a89bb5',
        'gh-neutral-muted': 'rgba(168,155,181,0.3)',
        'gh-accent-fg': '#00e5cc',
        'gh-accent-emphasis': '#00ffd5',
        'gh-accent-muted': 'rgba(0,229,204,0.3)',
        'gh-accent-subtle': '#1a3e3a',
        'gh-success-fg': '#7dfc00',
        'gh-success-emphasis': '#8fff00',
        'gh-success-muted': 'rgba(125,252,0,0.3)',
        'gh-success-subtle': '#2a4d1a',
        'gh-attention-fg': '#ffd700',
        'gh-attention-emphasis': '#ffed4e',
        'gh-attention-muted': 'rgba(255,215,0,0.3)',
        'gh-attention-subtle': '#4a3d1a',
        'gh-danger-fg': '#ff3864',
        'gh-danger-emphasis': '#ff5277',
        'gh-danger-subtle': '#4d1a2a',
        'gh-fg-default': '#f0e6ff',
        'gh-fg-muted': '#b8a5cc',
        'gh-fg-subtle': '#9b87ad',
        // Short aliases for convenience
        'canvas-default': '#2d1b2e',
        'canvas-subtle': '#3d2946',
        'canvas-inset': '#1f1626',
        'border-default': '#8b6d9c',
        'border-muted': '#5c4a68',
        'accent-fg': '#00e5cc',
        'accent-emphasis': '#00ffd5',
        'accent-subtle': '#1a3e3a',
        'success-fg': '#7dfc00',
        'success-emphasis': '#8fff00',
        'success-subtle': '#2a4d1a',
        'attention-fg': '#ffd700',
        'attention-emphasis': '#ffed4e',
        'attention-subtle': '#4a3d1a',
        'danger-fg': '#ff3864',
        'danger-emphasis': '#ff5277',
        'danger-subtle': '#4d1a2a',
        'fg-default': '#f0e6ff',
        'fg-muted': '#b8a5cc',
        // Dark mode (same as main theme for consistency)
        'gh-dark-canvas-default': '#2d1b2e',
        'gh-dark-canvas-subtle': '#3d2946',
        'gh-dark-canvas-inset': '#1f1626',
        'gh-dark-border-default': '#8b6d9c',
        'gh-dark-border-muted': '#5c4a68',
        'gh-dark-fg-default': '#f0e6ff',
        'gh-dark-fg-muted': '#b8a5cc',
        'gh-dark-accent-fg': '#00e5cc',
        'gh-dark-accent-emphasis': '#00ffd5',
      },
      fontFamily: {
        pixel: ['"Press Start 2P"', 'cursive'],
        retro: ['VT323', 'monospace'],
        sans: ['VT323', 'monospace'],
        mono: ['VT323', 'monospace'],
      },
      borderRadius: {
        'gh': '0px',
        'gh-lg': '0px',
      },
      boxShadow: {
        'gh': '4px 4px 0px rgba(0,0,0,0.5)',
        'gh-sm': '2px 2px 0px rgba(0,0,0,0.5)',
        'gh-md': '6px 6px 0px rgba(0,0,0,0.5)',
        'gh-lg': '8px 8px 0px rgba(0,0,0,0.5)',
        'pixel': 'inset -2px -2px 0px rgba(0,0,0,0.5), inset 2px 2px 0px rgba(255,255,255,0.2)',
      },
      animation: {
        'pixel-pulse': 'pixelPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 3s ease-in-out infinite',
        'swing': 'swing 0.6s ease-in-out infinite',
      },
      keyframes: {
        pixelPulse: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.7 },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        swing: {
          '0%, 100%': { transform: 'rotate(-15deg)' },
          '50%': { transform: 'rotate(15deg)' },
        },
      },
    },
  },
  plugins: [],
}
